### PR TITLE
Fix #102

### LINKED ISSUE #102: go-systemd  should be imported appropriately
- Riot version (or commit ref): bdbc256e4cbd
- Go version: 1.13.3

- Operating system and bit:
- Can you reproduce the bug at [Examples](https://github.com/go-ego/riot/tree/master/examples):
  - [x] Yes (provide example code)
  - [ ] No
  - [ ] Not relevant
- Provide example code:
 
```
$ go build -v .
go: finding github.com/go-ego/riot latest
go: github.com/go-ego/riot@v0.0.0-20191215221243-bdbc256e4cbd requires
        github.com/coreos/go-systemd@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

main.go is the example code in README.md

```
package main

import (
	"log"

	"github.com/go-ego/riot"
	"github.com/go-ego/riot/types"
)

var (
	// searcher is coroutine safe
	searcher = riot.Engine{}
)

func main() {
	// Init
	searcher.Init(types.EngineOpts{
		// Using:             4,
		NotUseGse: true,
	})
	defer searcher.Close()

	text := "Google Is Experimenting With Virtual Reality Advertising"
	text1 := `Google accidentally pushed Bluetooth update for Home
	speaker early`
	text2 := `Google is testing another Search results layout with 
	rounded cards, new colors, and the 4 mysterious colored dots again`

	// Add the document to the index, docId starts at 1
	searcher.Index("1", types.DocData{Content: text})
	searcher.Index("2", types.DocData{Content: text1}, false)
	searcher.IndexDoc("3", types.DocData{Content: text2}, true)

	// Wait for the index to refresh
	searcher.Flush()
	// engine.FlushIndex()

	// The search output format is found in the types.SearchResp structure
	log.Print(searcher.Search(types.SearchReq{Text: "google testing"}))
}
```

## Description

This project can't be imported by go mod.

### PR DESCRIPTION
**Pull request by liubog2008**
**Please provide Issues links to:**

- Issues: #102 

**Provide test code:**

```Go
        
```
    
## Description

...

### CODE REVIEW

**Comment by liubog2008** [comment]
@vcaesar

**Comment by iGoogle-ink** [comment]
Not yet merge?

**Comment by vcaesar** [comment]
Can't reproduce and can not run `go mod tiny`.

**Comment by leafney** [comment]
Waiting for merge.

**Pull request merged**
